# Generated by Django 4.1.4 on 2022-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, default='', upload_to='accounts/cover/%Y/%m/%d/', verbose_name='Imagem de usuário'),
        ),
    ]
