# Generated by Django 4.1.4 on 2022-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_img'),
        ('draws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to='accounts.profile'),
        ),
    ]
