# Generated by Django 4.1.3 on 2022-12-02 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draws', '0002_alter_draw_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draw',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
