# Generated by Django 4.1.4 on 2022-12-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_img'),
        ('draws', '0003_drawcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='accounts.profile'),
        ),
    ]
