# Generated by Django 4.1.3 on 2022-12-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0003_draw_like_draw_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Título'),
        ),
    ]
