# Generated by Django 4.1.4 on 2022-12-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0007_alter_drawcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawcomment',
            name='comment',
            field=models.TextField(verbose_name='Comentário'),
        ),
    ]
